[gcp_service_account]
type = "<TYPE_DO_JSON>"
project_id = "<PROJECT_ID_DO_JSON>"
private_key_id = "<PRIVATE_KEY_ID_DO_JSON>"
private_key = """
-----BEGIN PRIVATE KEY-----
<SUA_CHAVE_PRIVADA_AQUI>
-----END PRIVATE KEY-----
"""
client_email = "<CLIENT_EMAIL_DO_JSON>"
client_id = "<CLIENT_ID_DO_JSON>"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/oauth2/v4/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "<CLIENT_X509_CERT_URL_DO_JSON>"

SHEET_KEY = "<ID_DA_SUA_PLANILHA>"
